/**
 * 5 nashr profili (Maqola 2, AUDIT-17) — BITTA tanlov shrift, interval,
 * chegara, iqtibos uslubi, manbalar soni va raqamlashni beradi.
 *
 * Asos — tadqiqot: OAK qoidalari (TNR 14, 1.5, chegara 2/2/3/1.5 sm,
 * `[1; 25-b.]`, rasm nomi PASTDA, jadval nomi TEPADA), TATU xabarnomasi
 * (TNR 14, yakka interval, UDK, ≤15 varaq), FarDU (APA 7, ≥15 manba,
 * >50% oxirgi 5 yil), IEEE (raqamli iqtibos, raqamlangan bo'limlar),
 * konferensiya to'plamlari. O'zbekistonda YAGONA standart yo'q — shuning
 * uchun profil tizimi.
 */
import type { PublicationProfile, PublicationProfileId } from "./types";

export const PUBLICATION_PROFILES: Record<PublicationProfileId, PublicationProfile> = {
  oak: {
    id: "oak",
    label: { uz: "OAK jurnali", ru: "Журнал ОАК", en: "OAK (Uzbekistan HAC) journal" },
    hint: "TNR 14, 1.5 interval, chegara 2/2/3/1.5 sm, iqtibos [1; 25-b.], GOST + inglizcha REFERENCES, UDK",
    font: "Times New Roman",
    sizePt: 14,
    line: 1.5,
    marginsCm: { top: 2, bottom: 2, left: 3, right: 1.5 },
    cite: "gost",
    refsMin: 10,
    refsMax: 30,
    recentYearsMin: 5,
    recentShare: 0.4,
    secondEnglishList: true,
    udk: true,
    numberedSections: false,
    figureNumbering: "flat",
    tableSizePt: 10,
    refsSizePt: 12,
    refsLine: 1.15,
    abstractLine: 1.15,
    abstractWords: [150, 250],
    keywords: [5, 12],
  },
  university: {
    id: "university",
    label: { uz: "Universitet xabarnomasi", ru: "Вестник университета", en: "University bulletin" },
    hint: "TNR 14, yakka interval, UDK, iqtibos [1], ≤15 varaq (TATU xabarnomasi tipidagi)",
    font: "Times New Roman",
    sizePt: 14,
    line: 1,
    marginsCm: { top: 2, bottom: 2, left: 3, right: 1.5 },
    cite: "numeric",
    refsMin: 8,
    refsMax: 25,
    recentYearsMin: 5,
    recentShare: 0.4,
    secondEnglishList: false,
    udk: true,
    numberedSections: false,
    figureNumbering: "flat",
    tableSizePt: 12,
    refsSizePt: 12,
    refsLine: 1.0,
    abstractLine: 1.0,
    maxPages: 15,
    abstractWords: [100, 200],
    keywords: [5, 10],
  },
  apa: {
    id: "apa",
    label: { uz: "Xalqaro — APA 7", ru: "Международный — APA 7", en: "International — APA 7" },
    hint: "TNR 12, 1.5 interval, chegara 2.5 sm, iqtibos (Muallif, yil), APA 7 ro‘yxat, ≥15 manba, >50% oxirgi 5 yil",
    font: "Times New Roman",
    sizePt: 12,
    line: 1.5,
    marginsCm: { top: 2.5, bottom: 2.5, left: 2.5, right: 2.5 },
    cite: "apa7",
    refsMin: 15,
    refsMax: 60,
    recentYearsMin: 5,
    recentShare: 0.5,
    secondEnglishList: false,
    udk: false,
    numberedSections: false,
    figureNumbering: "flat",
    tableSizePt: 11,
    refsSizePt: 12,
    refsLine: 1.5,
    abstractLine: 1.5,
    abstractWords: [150, 250],
    keywords: [4, 6],
  },
  ieee: {
    id: "ieee",
    label: { uz: "IEEE / Elsevier", ru: "IEEE / Elsevier", en: "IEEE / Elsevier" },
    hint: "TNR 12, yakka interval, iqtibos [1] tartibida, raqamlangan bo‘limlar 1., 1.1., DOI majburiy",
    font: "Times New Roman",
    sizePt: 12,
    line: 1,
    marginsCm: { top: 2.5, bottom: 2.5, left: 2, right: 2 },
    cite: "ieee",
    refsMin: 15,
    refsMax: 60,
    recentYearsMin: 5,
    recentShare: 0.5,
    secondEnglishList: false,
    udk: false,
    numberedSections: true,
    figureNumbering: "flat",
    tableSizePt: 10,
    refsSizePt: 10,
    refsLine: 1.0,
    abstractLine: 1.0,
    abstractWords: [150, 250],
    keywords: [4, 6],
  },
  conference: {
    id: "conference",
    label: { uz: "Konferensiya to‘plami", ru: "Сборник конференции", en: "Conference proceedings" },
    hint: "TNR 12, yakka interval, qisqa; iqtibos [1]; ≤20 manba (tezisda ≤3)",
    font: "Times New Roman",
    sizePt: 12,
    line: 1,
    marginsCm: { top: 2, bottom: 2, left: 2.5, right: 2 },
    cite: "numeric",
    refsMin: 0,
    refsMax: 20,
    recentYearsMin: 5,
    recentShare: 0.3,
    secondEnglishList: false,
    udk: true,
    numberedSections: false,
    figureNumbering: "flat",
    tableSizePt: 10,
    refsSizePt: 10,
    refsLine: 1.0,
    abstractLine: 1.0,
    maxPages: 5,
    abstractWords: [80, 200],
    keywords: [3, 8],
  },
};

export function isPublicationProfileId(v: unknown): v is PublicationProfileId {
  return typeof v === "string" && Object.prototype.hasOwnProperty.call(PUBLICATION_PROFILES, v);
}

export function normalizePublicationProfile(v: unknown, fallback: PublicationProfileId = "oak"): PublicationProfileId {
  return isPublicationProfileId(v) ? v : fallback;
}
