import { isSlideThemeId, type SlideTheme, type SlideThemeId } from "./slide-types";

/**
 * 15 ta original vizual tizim — tijoriy shablon nusxasi emas.
 * Palitra va chrome: akademik, dars, STEM, biznes, ijodiy, minimal.
 */
export const SLIDE_THEMES: SlideTheme[] = [
  {
    id: "atlas",
    name: "Atlas",
    nameUz: "Universitet Atlas",
    group: "akademik",
    blurb: "Himoya va ilmiy taqdimot: to‘q ko‘k + oltin",
    bg: "#F7F4EC",
    surface: "#FFFFFF",
    text: "#0B1F3A",
    muted: "#5C6B7A",
    accent: "#C9A227",
    accent2: "#0B1F3A",
    titleBg: "#0B1F3A",
    titleText: "#F7F4EC",
    titleMuted: "#C9A227",
    chrome: "split",
    darkContent: false,
  },
  {
    id: "lumen",
    name: "Lumen",
    nameUz: "Ma’ruza Lumen",
    group: "talim",
    blurb: "Dars va seminar: toza yashil-ko‘k + qaymoq",
    bg: "#FFFBEB",
    surface: "#FFFFFF",
    text: "#134E4A",
    muted: "#5B7468",
    accent: "#0F766E",
    accent2: "#F59E0B",
    titleBg: "#0F766E",
    titleText: "#FFFBEB",
    titleMuted: "#FDE68A",
    chrome: "bar-top",
    darkContent: false,
  },
  {
    id: "graphite",
    name: "Graphite",
    nameUz: "Laboratoriya Grafit",
    group: "stem",
    blurb: "STEM va texnika: ko‘mir + sian",
    bg: "#111318",
    surface: "#1C1F27",
    text: "#E8EEF7",
    muted: "#9AA4B2",
    accent: "#22D3EE",
    accent2: "#64748B",
    titleBg: "#0B0D11",
    titleText: "#F8FAFC",
    titleMuted: "#22D3EE",
    chrome: "bar-left",
    darkContent: true,
  },
  {
    id: "parchment",
    name: "Parchment",
    nameUz: "Pergament",
    group: "akademik",
    blurb: "Adabiyot va tarix: bordo + pergament",
    bg: "#FAF3E0",
    surface: "#FFF8E8",
    text: "#3F1D1D",
    muted: "#7C5A4A",
    accent: "#7F1D1D",
    accent2: "#B45309",
    titleBg: "#4A1515",
    titleText: "#FAF3E0",
    titleMuted: "#E7C27A",
    chrome: "frame",
    darkContent: false,
  },
  {
    id: "orbit",
    name: "Orbit",
    nameUz: "Orbit Pitch",
    group: "biznes",
    blurb: "Zamonaviy pitch: qora + binafsha",
    bg: "#0C0A09",
    surface: "#1C1917",
    text: "#FAFAF9",
    muted: "#A8A29E",
    accent: "#8B5CF6",
    accent2: "#F97316",
    titleBg: "#0C0A09",
    titleText: "#FAFAF9",
    titleMuted: "#C4B5FD",
    chrome: "block",
    darkContent: true,
  },
  {
    id: "clinic",
    name: "Clinic",
    nameUz: "Klinika",
    group: "stem",
    blurb: "Tibbiyot va salomatlik: oq + tibbiy ko‘k",
    bg: "#F8FBFF",
    surface: "#FFFFFF",
    text: "#0C4A6E",
    muted: "#64748B",
    accent: "#0284C7",
    accent2: "#0EA5E9",
    titleBg: "#0369A1",
    titleText: "#F0F9FF",
    titleMuted: "#BAE6FD",
    chrome: "bar-top",
    darkContent: false,
  },
  {
    id: "forge",
    name: "Forge",
    nameUz: "Temirxona",
    group: "stem",
    blurb: "Muhandislik: po‘lat + amber",
    bg: "#1C1917",
    surface: "#292524",
    text: "#FAFAF9",
    muted: "#A8A29E",
    accent: "#F59E0B",
    accent2: "#78716C",
    titleBg: "#0C0A09",
    titleText: "#FFFBEB",
    titleMuted: "#FBBF24",
    chrome: "bar-left",
    darkContent: true,
  },
  {
    id: "grove",
    name: "Grove",
    nameUz: "Bog‘",
    group: "talim",
    blurb: "Ekologiya va tabiat: o‘rmon + qum",
    bg: "#F7F6EF",
    surface: "#FFFFFF",
    text: "#14532D",
    muted: "#5C6B52",
    accent: "#15803D",
    accent2: "#A16207",
    titleBg: "#14532D",
    titleText: "#ECFDF3",
    titleMuted: "#BBF7D0",
    chrome: "split",
    darkContent: false,
  },
  {
    id: "summit",
    name: "Summit",
    nameUz: "Sammit",
    group: "biznes",
    blurb: "Biznes tahlil: to‘q ko‘k + marjon",
    bg: "#F4F7FB",
    surface: "#FFFFFF",
    text: "#1E3A5F",
    muted: "#64748B",
    accent: "#EA580C",
    accent2: "#1E3A5F",
    titleBg: "#1E3A5F",
    titleText: "#FFF7ED",
    titleMuted: "#FDBA74",
    chrome: "bar-top",
    darkContent: false,
  },
  {
    id: "ink",
    name: "Ink",
    nameUz: "Siyoh Minimal",
    group: "minimal",
    blurb: "Keynote: qora-oq + bitta qizil nuqta",
    bg: "#FFFFFF",
    surface: "#FAFAFA",
    text: "#111111",
    muted: "#6B7280",
    accent: "#DC2626",
    accent2: "#111111",
    titleBg: "#111111",
    titleText: "#FFFFFF",
    titleMuted: "#FCA5A5",
    chrome: "block",
    darkContent: false,
  },
  {
    id: "slate",
    name: "Slate",
    nameUz: "Slanets Konferensiya",
    group: "akademik",
    blurb: "Ilmiy anjuman: slanets + osmon",
    bg: "#F1F5F9",
    surface: "#FFFFFF",
    text: "#0F172A",
    muted: "#64748B",
    accent: "#0284C7",
    accent2: "#334155",
    titleBg: "#334155",
    titleText: "#F8FAFC",
    titleMuted: "#7DD3FC",
    chrome: "bar-left",
    darkContent: false,
  },
  {
    id: "sakura",
    name: "Sakura",
    nameUz: "Sakura",
    group: "ijodiy",
    blurb: "Ijodiy taqdimot: pushti + yumshoq krem",
    bg: "#FFF1F2",
    surface: "#FFFFFF",
    text: "#881337",
    muted: "#9F1239",
    accent: "#DB2777",
    accent2: "#FB7185",
    titleBg: "#9D174D",
    titleText: "#FFF1F2",
    titleMuted: "#FBCFE8",
    chrome: "frame",
    darkContent: false,
  },
  {
    id: "legal",
    name: "Legal",
    nameUz: "Rasmiy",
    group: "minimal",
    blurb: "Rasmiy hujjat: zumrad + oltin",
    bg: "#F4F7F4",
    surface: "#FFFFFF",
    text: "#052E16",
    muted: "#3F6212",
    accent: "#047857",
    accent2: "#B45309",
    titleBg: "#064E3B",
    titleText: "#ECFDF5",
    titleMuted: "#FBBF24",
    chrome: "frame",
    darkContent: false,
  },
  {
    id: "aurora",
    name: "Aurora",
    nameUz: "Aurora Tech",
    group: "stem",
    blurb: "IT va innovatsiya: tun + yashil nurlanish",
    bg: "#0B1220",
    surface: "#111827",
    text: "#E2E8F0",
    muted: "#94A3B8",
    accent: "#34D399",
    accent2: "#38BDF8",
    titleBg: "#020617",
    titleText: "#ECFDF5",
    titleMuted: "#6EE7B7",
    chrome: "split",
    darkContent: true,
  },
  {
    id: "chalk",
    name: "Chalk",
    nameUz: "Doska",
    group: "talim",
    blurb: "Maktab darsi: to‘q yashil doska + oq bo‘r",
    bg: "#17301A",
    surface: "#1E3A21",
    text: "#F4F1E8",
    muted: "#C5D5B8",
    accent: "#FDE68A",
    accent2: "#86EFAC",
    titleBg: "#122416",
    titleText: "#F8F5E8",
    titleMuted: "#FDE68A",
    chrome: "frame",
    darkContent: true,
  },
];

export const SLIDE_THEME_BY_ID = Object.fromEntries(SLIDE_THEMES.map((t) => [t.id, t])) as Record<
  SlideThemeId,
  SlideTheme
>;

export function getSlideTheme(id?: string | null): SlideTheme {
  if (id && isSlideThemeId(id)) return SLIDE_THEME_BY_ID[id];
  return SLIDE_THEME_BY_ID.atlas;
}

export const SLIDE_THEME_GROUPS: { id: SlideTheme["group"]; label: string }[] = [
  { id: "akademik", label: "Akademik" },
  { id: "talim", label: "Ta’lim" },
  { id: "stem", label: "STEM" },
  { id: "biznes", label: "Biznes" },
  { id: "ijodiy", label: "Ijodiy" },
  { id: "minimal", label: "Minimal" },
];
